// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: common.sql

package database

import (
	"context"
)

const checkDBReady = `-- name: CheckDBReady :one
SELECT 1
`

func (q *Queries) CheckDBReady(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkDBReady)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
