// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: form_responses.sql

package database

import (
	"context"
)

const listAllFormResponses = `-- name: ListAllFormResponses :many
SELECT
    id, settings_id, first_name, last_name, email, country_code, phone, id_type, id_value, meal_type, meals_count, meal_price, event_type, sessions_count, session_price, arrival_date, departure_date, medical_insurance, emergency_contact_name, emergency_contact_country_code, emergency_contact_phone, emergency_contact_email, currency, payment_id, payment_status, payment_amount, created_at, updated_at
FROM form_responses
WHERE
    settings_id = ?
ORDER BY created_at, id
`

func (q *Queries) ListAllFormResponses(ctx context.Context, settingsID string) ([]FormResponse, error) {
	rows, err := q.db.QueryContext(ctx, listAllFormResponses, settingsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormResponse{}
	for rows.Next() {
		var i FormResponse
		if err := rows.Scan(
			&i.ID,
			&i.SettingsID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.CountryCode,
			&i.Phone,
			&i.IDType,
			&i.IDValue,
			&i.MealType,
			&i.MealsCount,
			&i.MealPrice,
			&i.EventType,
			&i.SessionsCount,
			&i.SessionPrice,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.MedicalInsurance,
			&i.EmergencyContactName,
			&i.EmergencyContactCountryCode,
			&i.EmergencyContactPhone,
			&i.EmergencyContactEmail,
			&i.Currency,
			&i.PaymentID,
			&i.PaymentStatus,
			&i.PaymentAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormResponsesPaged = `-- name: ListFormResponsesPaged :many
SELECT
    id, settings_id, first_name, last_name, email, country_code, phone, id_type, id_value, meal_type, meals_count, meal_price, event_type, sessions_count, session_price, arrival_date, departure_date, medical_insurance, emergency_contact_name, emergency_contact_country_code, emergency_contact_phone, emergency_contact_email, currency, payment_id, payment_status, payment_amount, created_at, updated_at
FROM form_responses
WHERE
    settings_id = ?
ORDER BY created_at, id
LIMIT ?
OFFSET ?
`

type ListFormResponsesPagedParams struct {
	SettingsID string `json:"settings_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListFormResponsesPaged(ctx context.Context, arg ListFormResponsesPagedParams) ([]FormResponse, error) {
	rows, err := q.db.QueryContext(ctx, listFormResponsesPaged, arg.SettingsID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormResponse{}
	for rows.Next() {
		var i FormResponse
		if err := rows.Scan(
			&i.ID,
			&i.SettingsID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.CountryCode,
			&i.Phone,
			&i.IDType,
			&i.IDValue,
			&i.MealType,
			&i.MealsCount,
			&i.MealPrice,
			&i.EventType,
			&i.SessionsCount,
			&i.SessionPrice,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.MedicalInsurance,
			&i.EmergencyContactName,
			&i.EmergencyContactCountryCode,
			&i.EmergencyContactPhone,
			&i.EmergencyContactEmail,
			&i.Currency,
			&i.PaymentID,
			&i.PaymentStatus,
			&i.PaymentAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuccessFormResponses = `-- name: ListSuccessFormResponses :many
SELECT
    id, settings_id, first_name, last_name, email, country_code, phone, id_type, id_value, meal_type, meals_count, meal_price, event_type, sessions_count, session_price, arrival_date, departure_date, medical_insurance, emergency_contact_name, emergency_contact_country_code, emergency_contact_phone, emergency_contact_email, currency, payment_id, payment_status, payment_amount, created_at, updated_at
FROM form_responses
WHERE
    settings_id = ? AND
    payment_status IN ('NOT_NEEDED', 'SUCCESS')
ORDER BY created_at, id
`

func (q *Queries) ListSuccessFormResponses(ctx context.Context, settingsID string) ([]FormResponse, error) {
	rows, err := q.db.QueryContext(ctx, listSuccessFormResponses, settingsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormResponse{}
	for rows.Next() {
		var i FormResponse
		if err := rows.Scan(
			&i.ID,
			&i.SettingsID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.CountryCode,
			&i.Phone,
			&i.IDType,
			&i.IDValue,
			&i.MealType,
			&i.MealsCount,
			&i.MealPrice,
			&i.EventType,
			&i.SessionsCount,
			&i.SessionPrice,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.MedicalInsurance,
			&i.EmergencyContactName,
			&i.EmergencyContactCountryCode,
			&i.EmergencyContactPhone,
			&i.EmergencyContactEmail,
			&i.Currency,
			&i.PaymentID,
			&i.PaymentStatus,
			&i.PaymentAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
