// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meals.sql

package database

import (
	"context"
	"database/sql"
)

const createMeal = `-- name: CreateMeal :execresult
INSERT INTO meals (
    id,
    settings_id,
    title
) VALUES (
   UUID(), ?, ?
)
`

type CreateMealParams struct {
	SettingsID string `json:"settings_id"`
	Title      string `json:"title"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMeal, arg.SettingsID, arg.Title)
}

const deleteMeal = `-- name: DeleteMeal :execresult
DELETE FROM meals
WHERE id = ? AND settings_id = ?
`

type DeleteMealParams struct {
	ID         string `json:"id"`
	SettingsID string `json:"settings_id"`
}

func (q *Queries) DeleteMeal(ctx context.Context, arg DeleteMealParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteMeal, arg.ID, arg.SettingsID)
}

const updateMeal = `-- name: UpdateMeal :execresult
UPDATE meals
SET
    title = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND settings_id = ?
`

type UpdateMealParams struct {
	Title      string `json:"title"`
	ID         string `json:"id"`
	SettingsID string `json:"settings_id"`
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateMeal, arg.Title, arg.ID, arg.SettingsID)
}
