// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meals.sql

package database

import (
	"context"
	"database/sql"
)

const createMeal = `-- name: CreateMeal :execresult
INSERT INTO meals (
    id,
    settings_id,
    title
) VALUES (
   ?, ?, ?
)
`

type CreateMealParams struct {
	ID         string `json:"id"`
	SettingsID string `json:"settings_id"`
	Title      string `json:"title"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMeal, arg.ID, arg.SettingsID, arg.Title)
}

const deleteMeal = `-- name: DeleteMeal :execresult
DELETE FROM meals
WHERE id = ? AND settings_id = ?
`

type DeleteMealParams struct {
	ID         string `json:"id"`
	SettingsID string `json:"settings_id"`
}

func (q *Queries) DeleteMeal(ctx context.Context, arg DeleteMealParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteMeal, arg.ID, arg.SettingsID)
}

const listMealsBySettingsId = `-- name: ListMealsBySettingsId :many
SELECT
    id,
    title
FROM meals
WHERE settings_id = ?
ORDER BY id
`

type ListMealsBySettingsIdRow struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) ListMealsBySettingsId(ctx context.Context, settingsID string) ([]ListMealsBySettingsIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listMealsBySettingsId, settingsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMealsBySettingsIdRow{}
	for rows.Next() {
		var i ListMealsBySettingsIdRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeal = `-- name: UpdateMeal :execresult
UPDATE meals
SET
    title = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND settings_id = ?
`

type UpdateMealParams struct {
	Title      string `json:"title"`
	ID         string `json:"id"`
	SettingsID string `json:"settings_id"`
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateMeal, arg.Title, arg.ID, arg.SettingsID)
}
