// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type FormResponse struct {
	ID                          string         `json:"id"`
	SettingsID                  string         `json:"settings_id"`
	FirstName                   string         `json:"first_name"`
	LastName                    string         `json:"last_name"`
	Email                       string         `json:"email"`
	CountryCode                 string         `json:"country_code"`
	Phone                       string         `json:"phone"`
	IDType                      string         `json:"id_type"`
	IDValue                     string         `json:"id_value"`
	MealType                    sql.NullString `json:"meal_type"`
	MealsCount                  sql.NullInt32  `json:"meals_count"`
	MealPrice                   string         `json:"meal_price"`
	EventType                   sql.NullString `json:"event_type"`
	SessionsCount               sql.NullInt32  `json:"sessions_count"`
	SessionPrice                string         `json:"session_price"`
	ArrivalDate                 sql.NullTime   `json:"arrival_date"`
	DepartureDate               sql.NullTime   `json:"departure_date"`
	MedicalInsurance            sql.NullString `json:"medical_insurance"`
	EmergencyContactName        sql.NullString `json:"emergency_contact_name"`
	EmergencyContactCountryCode sql.NullString `json:"emergency_contact_country_code"`
	EmergencyContactPhone       sql.NullString `json:"emergency_contact_phone"`
	EmergencyContactEmail       sql.NullString `json:"emergency_contact_email"`
	Currency                    sql.NullString `json:"currency"`
	PaymentID                   sql.NullString `json:"payment_id"`
	PaymentStatus               sql.NullString `json:"payment_status"`
	PaymentAmount               string         `json:"payment_amount"`
	CreatedAt                   time.Time      `json:"created_at"`
	UpdatedAt                   time.Time      `json:"updated_at"`
}

type Meal struct {
	ID         string    `json:"id"`
	SettingsID string    `json:"settings_id"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type RateLimit struct {
	Ip          string `json:"ip"`
	WindowStart int32  `json:"window_start"`
	Count       int32  `json:"count"`
}

type Session struct {
	ID          string    `json:"id"`
	SettingsID  string    `json:"settings_id"`
	Title       string    `json:"title"`
	SessionTime time.Time `json:"session_time"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Setting struct {
	ID              string         `json:"id"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	FormType        string         `json:"form_type"`
	StartDate       time.Time      `json:"start_date"`
	EndDate         time.Time      `json:"end_date"`
	MealPricePen    string         `json:"meal_price_pen"`
	MealPriceUsd    string         `json:"meal_price_usd"`
	SessionPricePen string         `json:"session_price_pen"`
	SessionPriceUsd string         `json:"session_price_usd"`
	Disclaimer      sql.NullString `json:"disclaimer"`
	Active          bool           `json:"active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
