// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :execresult
INSERT INTO sessions (
    id,
    settings_id,
    title,
	session_time
) VALUES (
   ?, ?, ?, ?
)
`

type CreateSessionParams struct {
	ID          string    `json:"id"`
	SettingsID  string    `json:"settings_id"`
	Title       string    `json:"title"`
	SessionTime time.Time `json:"session_time"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.SettingsID,
		arg.Title,
		arg.SessionTime,
	)
}

const deleteSession = `-- name: DeleteSession :execresult
DELETE FROM sessions
WHERE id = ? AND settings_id = ?
`

type DeleteSessionParams struct {
	ID         string `json:"id"`
	SettingsID string `json:"settings_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSession, arg.ID, arg.SettingsID)
}

const listSessionsBySettingsId = `-- name: ListSessionsBySettingsId :many
SELECT
    id,
    title,
    session_time
FROM sessions
WHERE settings_id = ?
ORDER BY id
`

type ListSessionsBySettingsIdRow struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	SessionTime time.Time `json:"session_time"`
}

func (q *Queries) ListSessionsBySettingsId(ctx context.Context, settingsID string) ([]ListSessionsBySettingsIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsBySettingsId, settingsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsBySettingsIdRow{}
	for rows.Next() {
		var i ListSessionsBySettingsIdRow
		if err := rows.Scan(&i.ID, &i.Title, &i.SessionTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :execresult
UPDATE sessions
SET
    title = ?,
    session_time = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND settings_id = ?
`

type UpdateSessionParams struct {
	Title       string    `json:"title"`
	SessionTime time.Time `json:"session_time"`
	ID          string    `json:"id"`
	SettingsID  string    `json:"settings_id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSession,
		arg.Title,
		arg.SessionTime,
		arg.ID,
		arg.SettingsID,
	)
}
