// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :execresult
INSERT INTO sessions (
    id,
    settings_id,
    title,
	session_time
) VALUES (
   UUID(), ?, ?, ?
)
`

type CreateSessionParams struct {
	SettingsID  string    `json:"settings_id"`
	Title       string    `json:"title"`
	SessionTime time.Time `json:"session_time"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSession, arg.SettingsID, arg.Title, arg.SessionTime)
}

const deleteSession = `-- name: DeleteSession :execresult
DELETE FROM sessions
WHERE id = ? AND settings_id = ?
`

type DeleteSessionParams struct {
	ID         string `json:"id"`
	SettingsID string `json:"settings_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSession, arg.ID, arg.SettingsID)
}

const updateSession = `-- name: UpdateSession :execresult
UPDATE sessions
SET
    title = ?,
    session_time = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND settings_id = ?
`

type UpdateSessionParams struct {
	Title       string    `json:"title"`
	SessionTime time.Time `json:"session_time"`
	ID          string    `json:"id"`
	SettingsID  string    `json:"settings_id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSession,
		arg.Title,
		arg.SessionTime,
		arg.ID,
		arg.SettingsID,
	)
}
