// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countSettings = `-- name: CountSettings :one
SELECT COUNT(*)
FROM settings
WHERE end_date > NOW()
`

func (q *Queries) CountSettings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSettings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSettings = `-- name: CreateSettings :execresult
INSERT INTO settings (
    id,
    title,
    description,
    form_type,
    start_date,
    end_date,
    meal_price_pen,
    meal_price_usd,
    session_price_pen,
    session_price_usd
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateSettingsParams struct {
	ID              string    `json:"id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	FormType        string    `json:"form_type"`
	StartDate       time.Time `json:"start_date"`
	EndDate         time.Time `json:"end_date"`
	MealPricePen    string    `json:"meal_price_pen"`
	MealPriceUsd    string    `json:"meal_price_usd"`
	SessionPricePen string    `json:"session_price_pen"`
	SessionPriceUsd string    `json:"session_price_usd"`
}

func (q *Queries) CreateSettings(ctx context.Context, arg CreateSettingsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSettings,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.FormType,
		arg.StartDate,
		arg.EndDate,
		arg.MealPricePen,
		arg.MealPriceUsd,
		arg.SessionPricePen,
		arg.SessionPriceUsd,
	)
}

const deleteSettings = `-- name: DeleteSettings :execresult
DELETE FROM settings
WHERE id = ?
`

func (q *Queries) DeleteSettings(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSettings, id)
}

const getSettingsByID = `-- name: GetSettingsByID :one
SELECT
    id, title, description, form_type, start_date, end_date, meal_price_pen, meal_price_usd, session_price_pen, session_price_usd, disclaimer, active, created_at, updated_at
FROM settings
WHERE
    end_date > NOW() AND
    id = ?
`

func (q *Queries) GetSettingsByID(ctx context.Context, id string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingsByID, id)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.FormType,
		&i.StartDate,
		&i.EndDate,
		&i.MealPricePen,
		&i.MealPriceUsd,
		&i.SessionPricePen,
		&i.SessionPriceUsd,
		&i.Disclaimer,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettingsPaged = `-- name: ListSettingsPaged :many
SELECT
    sett.id as id,
    sett.form_type,
    sett.title,
    sett.start_date,
    sett.end_date,
    COALESCE(m.meal_count, 0) AS meal_count,
    COALESCE(s.session_count, 0) AS session_count,
    active
FROM settings sett
LEFT JOIN (
    SELECT settings_id, COUNT(*) AS meal_count
    FROM meals
    GROUP BY settings_id
) m ON sett.id = m.settings_id
LEFT JOIN (
    SELECT settings_id, COUNT(*) AS session_count
    FROM sessions
    GROUP BY settings_id
) s ON sett.id = s.settings_id
WHERE sett.end_date > NOW()
ORDER BY sett.start_date
LIMIT ?
OFFSET ?
`

type ListSettingsPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSettingsPagedRow struct {
	ID           string    `json:"id"`
	FormType     string    `json:"form_type"`
	Title        string    `json:"title"`
	StartDate    time.Time `json:"start_date"`
	EndDate      time.Time `json:"end_date"`
	MealCount    int64     `json:"meal_count"`
	SessionCount int64     `json:"session_count"`
	Active       bool      `json:"active"`
}

func (q *Queries) ListSettingsPaged(ctx context.Context, arg ListSettingsPagedParams) ([]ListSettingsPagedRow, error) {
	rows, err := q.db.QueryContext(ctx, listSettingsPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettingsPagedRow{}
	for rows.Next() {
		var i ListSettingsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.FormType,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.MealCount,
			&i.SessionCount,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActiveSettings = `-- name: UpdateActiveSettings :execresult
UPDATE settings
SET
    active = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateActiveSettingsParams struct {
	Active bool   `json:"active"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateActiveSettings(ctx context.Context, arg UpdateActiveSettingsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateActiveSettings, arg.Active, arg.ID)
}

const updateSettings = `-- name: UpdateSettings :execresult
UPDATE settings
SET
    title = ?,
    description = ?,
    start_date = ?,
    end_date = ?,
    meal_price_pen = ?,
    meal_price_usd = ?,
    session_price_pen = ?,
    session_price_usd = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSettingsParams struct {
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	StartDate       time.Time `json:"start_date"`
	EndDate         time.Time `json:"end_date"`
	MealPricePen    string    `json:"meal_price_pen"`
	MealPriceUsd    string    `json:"meal_price_usd"`
	SessionPricePen string    `json:"session_price_pen"`
	SessionPriceUsd string    `json:"session_price_usd"`
	ID              string    `json:"id"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSettings,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.MealPricePen,
		arg.MealPriceUsd,
		arg.SessionPricePen,
		arg.SessionPriceUsd,
		arg.ID,
	)
}
