// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
	"fmt"
	"io"
	"sync/atomic"

	"github.com/go-sql-driver/mysql"
	"github.com/hexon/mysqltsv"
)

var readerHandlerSequenceForCreateAddon uint32 = 1

func convertRowsForCreateAddon(w *io.PipeWriter, arg []CreateAddonParams) {
	e := mysqltsv.NewEncoder(w, 9, nil)
	for _, row := range arg {
		e.AppendString(row.ID)
		e.AppendString(row.FormID)
		e.AppendString(row.Title)
		e.AppendValue(row.AddonType)
		e.AppendValue(row.SortOrder)
		e.AppendString(row.Price)
		e.AppendString(row.Currency)
		e.AppendValue(row.DateTime)
		e.AppendValue(row.Hint)
	}
	w.CloseWithError(e.Close())
}

// CreateAddon uses MySQL's LOAD DATA LOCAL INFILE and is not atomic.
//
// Errors and duplicate keys are treated as warnings and insertion will
// continue, even without an error for some cases.  Use this in a transaction
// and use SHOW WARNINGS to check for any problems and roll back if you want to.
//
// Check the documentation for more information:
// https://dev.mysql.com/doc/refman/8.0/en/load-data.html#load-data-error-handling
func (q *Queries) CreateAddon(ctx context.Context, arg []CreateAddonParams) (int64, error) {
	pr, pw := io.Pipe()
	defer pr.Close()
	rh := fmt.Sprintf("CreateAddon_%d", atomic.AddUint32(&readerHandlerSequenceForCreateAddon, 1))
	mysql.RegisterReaderHandler(rh, func() io.Reader { return pr })
	defer mysql.DeregisterReaderHandler(rh)
	go convertRowsForCreateAddon(pw, arg)
	// The string interpolation is necessary because LOAD DATA INFILE requires
	// the file name to be given as a literal string.
	result, err := q.db.ExecContext(ctx, fmt.Sprintf("LOAD DATA LOCAL INFILE '%s' INTO TABLE `addons` %s (id, form_id, title, addon_type, sort_order, price, currency, date_time, hint)", "Reader::"+rh, mysqltsv.Escaping))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
