// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package database

import (
	"context"
	"database/sql"
	"strings"
)

const dashboardAddons = `-- name: DashboardAddons :many
SELECT
    a.id,
    a.title,
    a.addon_type,
    a.price,
    a.currency,
    a.date_time,
    COUNT(oi.id) AS order_count
FROM addons a
LEFT JOIN order_items oi ON oi.addon_id = a.id
WHERE a.form_id IN (/*SLICE:ids*/?) AND a.active = TRUE
GROUP BY a.id
ORDER BY a.form_id, a.sort_order ASC
`

type DashboardAddonsRow struct {
	ID         string
	Title      string
	AddonType  AddonsAddonType
	Price      string
	Currency   string
	DateTime   sql.NullTime
	OrderCount int64
}

func (q *Queries) DashboardAddons(ctx context.Context, ids []string) ([]DashboardAddonsRow, error) {
	query := dashboardAddons
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardAddonsRow{}
	for rows.Next() {
		var i DashboardAddonsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AddonType,
			&i.Price,
			&i.Currency,
			&i.DateTime,
			&i.OrderCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardFormOrders = `-- name: DashboardFormOrders :many
SELECT
    o.currency currency,
    COUNT(DISTINCT f.id) form_count,
    COUNT(DISTINCT o.id) order_count,
    COALESCE(CAST(SUM(CASE WHEN o.status = 'CONFIRMED' THEN o.amount ELSE 0 END) AS DECIMAL(10,2)), 0) revenue,
    COALESCE(CAST(SUM(CASE WHEN o.status = 'DRAFT' THEN 1 ELSE 0 END) AS SIGNED), 0) draft_count,
    COALESCE(CAST(SUM(CASE WHEN o.status = 'CONFIRMED' THEN 1 ELSE 0 END) AS SIGNED), 0) confirmed_count,
    COALESCE(CAST(SUM(CASE WHEN o.status = 'CANCELLED' THEN 1 ELSE 0 END) AS SIGNED), 0) cancelled_count,
    COALESCE(CAST(SUM(CASE WHEN o.status = 'ON_SITE' THEN 1 ELSE 0 END) AS SIGNED), 0) on_site_count
FROM forms f
JOIN orders o ON o.form_id = f.id AND o.status IN (/*SLICE:status*/?)
WHERE f.id IN (/*SLICE:ids*/?)
GROUP BY o.currency
`

type DashboardFormOrdersParams struct {
	Status []OrdersStatus
	Ids    []string
}

type DashboardFormOrdersRow struct {
	Currency       string
	FormCount      int64
	OrderCount     int64
	Revenue        interface{}
	DraftCount     interface{}
	ConfirmedCount interface{}
	CancelledCount interface{}
	OnSiteCount    interface{}
}

func (q *Queries) DashboardFormOrders(ctx context.Context, arg DashboardFormOrdersParams) ([]DashboardFormOrdersRow, error) {
	query := dashboardFormOrders
	var queryParams []interface{}
	if len(arg.Status) > 0 {
		for _, v := range arg.Status {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:status*/?", strings.Repeat(",?", len(arg.Status))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:status*/?", "NULL", 1)
	}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardFormOrdersRow{}
	for rows.Next() {
		var i DashboardFormOrdersRow
		if err := rows.Scan(
			&i.Currency,
			&i.FormCount,
			&i.OrderCount,
			&i.Revenue,
			&i.DraftCount,
			&i.ConfirmedCount,
			&i.CancelledCount,
			&i.OnSiteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardListForms = `-- name: DashboardListForms :many
SELECT
    id,
    title
FROM forms
WHERE active = true AND end_date >= DATE_SUB(UTC_DATE(), INTERVAL 12 MONTH)
ORDER BY end_date DESC
LIMIT ?
`

type DashboardListFormsRow struct {
	ID    string
	Title string
}

func (q *Queries) DashboardListForms(ctx context.Context, limit int32) ([]DashboardListFormsRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardListForms, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardListFormsRow{}
	for rows.Next() {
		var i DashboardListFormsRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardSubmissions = `-- name: DashboardSubmissions :many
SELECT
    s.first_name,
    s.last_name,
    s.created_at,
    f.title,
    o.status
FROM submissions s
JOIN forms f ON f.id = s.form_id
JOIN orders o ON o.submission_id = s.id AND o.status IN (/*SLICE:status*/?)
WHERE f.id IN (/*SLICE:ids*/?)
ORDER BY s.created_at DESC
LIMIT 10
`

type DashboardSubmissionsParams struct {
	Status []OrdersStatus
	Ids    []string
}

type DashboardSubmissionsRow struct {
	FirstName string
	LastName  string
	CreatedAt sql.NullTime
	Title     string
	Status    OrdersStatus
}

func (q *Queries) DashboardSubmissions(ctx context.Context, arg DashboardSubmissionsParams) ([]DashboardSubmissionsRow, error) {
	query := dashboardSubmissions
	var queryParams []interface{}
	if len(arg.Status) > 0 {
		for _, v := range arg.Status {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:status*/?", strings.Repeat(",?", len(arg.Status))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:status*/?", "NULL", 1)
	}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardSubmissionsRow{}
	for rows.Next() {
		var i DashboardSubmissionsRow
		if err := rows.Scan(
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.Title,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
