// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: form_addons.sql

package database

import (
	"context"
	"database/sql"
)

const createAddon = `-- name: CreateAddon :exec
INSERT INTO addons (
    id, 
    form_id, 
    title, 
    addon_type, 
    sort_order, 
    price, 
    currency, 
    date_time, 
    hint
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateAddonParams struct {
	ID        string
	FormID    string
	Title     string
	AddonType AddonsAddonType
	SortOrder int32
	Price     string
	Currency  string
	DateTime  sql.NullTime
	Hint      sql.NullString
}

func (q *Queries) CreateAddon(ctx context.Context, arg CreateAddonParams) error {
	_, err := q.db.ExecContext(ctx, createAddon,
		arg.ID,
		arg.FormID,
		arg.Title,
		arg.AddonType,
		arg.SortOrder,
		arg.Price,
		arg.Currency,
		arg.DateTime,
		arg.Hint,
	)
	return err
}

const getAddonsByFormID = `-- name: GetAddonsByFormID :many
SELECT
    id,
    title,
    addon_type,
    sort_order,
    price,
    currency,
    date_time,
    hint,
    active
FROM addons
WHERE form_id = ? AND active = TRUE
ORDER BY addon_type DESC, sort_order ASC
`

type GetAddonsByFormIDRow struct {
	ID        string
	Title     string
	AddonType AddonsAddonType
	SortOrder int32
	Price     string
	Currency  string
	DateTime  sql.NullTime
	Hint      sql.NullString
	Active    bool
}

func (q *Queries) GetAddonsByFormID(ctx context.Context, formID string) ([]GetAddonsByFormIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAddonsByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAddonsByFormIDRow{}
	for rows.Next() {
		var i GetAddonsByFormIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AddonType,
			&i.SortOrder,
			&i.Price,
			&i.Currency,
			&i.DateTime,
			&i.Hint,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddonStatus = `-- name: UpdateAddonStatus :exec
UPDATE addons
SET active = ?
WHERE id = ?
`

type UpdateAddonStatusParams struct {
	Active bool
	ID     string
}

func (q *Queries) UpdateAddonStatus(ctx context.Context, arg UpdateAddonStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAddonStatus, arg.Active, arg.ID)
	return err
}

const upsertAddon = `-- name: UpsertAddon :exec
INSERT INTO addons (
    id, 
    form_id, 
    title, 
    addon_type, 
    sort_order, 
    price, 
    currency, 
    date_time, 
    hint
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
) ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    price = VALUES(price),
    currency = VALUES(currency),
    sort_order = VALUES(sort_order),
    date_time = VALUES(date_time),
    hint = VALUES(hint)
`

type UpsertAddonParams struct {
	ID        string
	FormID    string
	Title     string
	AddonType AddonsAddonType
	SortOrder int32
	Price     string
	Currency  string
	DateTime  sql.NullTime
	Hint      sql.NullString
}

func (q *Queries) UpsertAddon(ctx context.Context, arg UpsertAddonParams) error {
	_, err := q.db.ExecContext(ctx, upsertAddon,
		arg.ID,
		arg.FormID,
		arg.Title,
		arg.AddonType,
		arg.SortOrder,
		arg.Price,
		arg.Currency,
		arg.DateTime,
		arg.Hint,
	)
	return err
}
