// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forms.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countForms = `-- name: CountForms :one
SELECT COUNT(*)
FROM forms
WHERE active = ?
`

func (q *Queries) CountForms(ctx context.Context, active bool) (int64, error) {
	row := q.db.QueryRowContext(ctx, countForms, active)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForm = `-- name: CreateForm :exec
INSERT INTO forms (
    id, 
    title, 
    description, 
    form_type,
    start_date, 
    end_date
) VALUES (
    ?, 
    ?, 
    ?, 
    ?, 
    ?, 
    ? 
)
`

type CreateFormParams struct {
	ID          string
	Title       string
	Description sql.NullString
	FormType    FormsFormType
	StartDate   time.Time
	EndDate     time.Time
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) error {
	_, err := q.db.ExecContext(ctx, createForm,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.FormType,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const getFormByID = `-- name: GetFormByID :one
SELECT
    id,
    title,
    form_type,
    description,
    start_date,
    end_date
FROM forms
WHERE id = ?
`

type GetFormByIDRow struct {
	ID          string
	Title       string
	FormType    FormsFormType
	Description sql.NullString
	StartDate   time.Time
	EndDate     time.Time
}

func (q *Queries) GetFormByID(ctx context.Context, id string) (GetFormByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFormByID, id)
	var i GetFormByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FormType,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const listForms = `-- name: ListForms :many
SELECT 
    id, 
    title, 
    form_type, 
    start_date, 
    end_date, 
    active
FROM forms
WHERE active = ?
ORDER BY start_date DESC, id DESC
LIMIT ?
OFFSET ?
`

type ListFormsParams struct {
	Active bool
	Limit  int32
	Offset int32
}

type ListFormsRow struct {
	ID        string
	Title     string
	FormType  FormsFormType
	StartDate time.Time
	EndDate   time.Time
	Active    bool
}

func (q *Queries) ListForms(ctx context.Context, arg ListFormsParams) ([]ListFormsRow, error) {
	rows, err := q.db.QueryContext(ctx, listForms, arg.Active, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFormsRow{}
	for rows.Next() {
		var i ListFormsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FormType,
			&i.StartDate,
			&i.EndDate,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForm = `-- name: UpdateForm :exec
UPDATE forms
SET 
    form_type = ?,
    title = ?,
    description = ?,
    start_date = ?,
    end_date = ?
WHERE id = ?
`

type UpdateFormParams struct {
	FormType    FormsFormType
	Title       string
	Description sql.NullString
	StartDate   time.Time
	EndDate     time.Time
	ID          string
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) error {
	_, err := q.db.ExecContext(ctx, updateForm,
		arg.FormType,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	return err
}

const updateFormStatus = `-- name: UpdateFormStatus :exec
UPDATE forms
SET active = ?
WHERE id = ?
`

type UpdateFormStatusParams struct {
	Active bool
	ID     string
}

func (q *Queries) UpdateFormStatus(ctx context.Context, arg UpdateFormStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFormStatus, arg.Active, arg.ID)
	return err
}
