// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type AddonsAddonType string

const (
	AddonsAddonTypeSESSION             AddonsAddonType = "SESSION"
	AddonsAddonTypeMEAL                AddonsAddonType = "MEAL"
	AddonsAddonTypeALLSESSIONSDISCOUNT AddonsAddonType = "ALL_SESSIONS_DISCOUNT"
	AddonsAddonTypeEARLYDISCOUNT       AddonsAddonType = "EARLY_DISCOUNT"
)

func (e *AddonsAddonType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AddonsAddonType(s)
	case string:
		*e = AddonsAddonType(s)
	default:
		return fmt.Errorf("unsupported scan type for AddonsAddonType: %T", src)
	}
	return nil
}

type NullAddonsAddonType struct {
	AddonsAddonType AddonsAddonType
	Valid           bool // Valid is true if AddonsAddonType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAddonsAddonType) Scan(value interface{}) error {
	if value == nil {
		ns.AddonsAddonType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AddonsAddonType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAddonsAddonType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AddonsAddonType), nil
}

func (e AddonsAddonType) Valid() bool {
	switch e {
	case AddonsAddonTypeSESSION,
		AddonsAddonTypeMEAL,
		AddonsAddonTypeALLSESSIONSDISCOUNT,
		AddonsAddonTypeEARLYDISCOUNT:
		return true
	}
	return false
}

type FormsFormType string

const (
	FormsFormTypeCONFERENCE FormsFormType = "CONFERENCE"
	FormsFormTypeCOURSE     FormsFormType = "COURSE"
	FormsFormTypeSPECIAL    FormsFormType = "SPECIAL"
)

func (e *FormsFormType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FormsFormType(s)
	case string:
		*e = FormsFormType(s)
	default:
		return fmt.Errorf("unsupported scan type for FormsFormType: %T", src)
	}
	return nil
}

type NullFormsFormType struct {
	FormsFormType FormsFormType
	Valid         bool // Valid is true if FormsFormType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFormsFormType) Scan(value interface{}) error {
	if value == nil {
		ns.FormsFormType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FormsFormType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFormsFormType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FormsFormType), nil
}

func (e FormsFormType) Valid() bool {
	switch e {
	case FormsFormTypeCONFERENCE,
		FormsFormTypeCOURSE,
		FormsFormTypeSPECIAL:
		return true
	}
	return false
}

type OrderItemsAddonType string

const (
	OrderItemsAddonTypeSESSION             OrderItemsAddonType = "SESSION"
	OrderItemsAddonTypeMEAL                OrderItemsAddonType = "MEAL"
	OrderItemsAddonTypeALLSESSIONSDISCOUNT OrderItemsAddonType = "ALL_SESSIONS_DISCOUNT"
	OrderItemsAddonTypeEARLYDISCOUNT       OrderItemsAddonType = "EARLY_DISCOUNT"
)

func (e *OrderItemsAddonType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderItemsAddonType(s)
	case string:
		*e = OrderItemsAddonType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderItemsAddonType: %T", src)
	}
	return nil
}

type NullOrderItemsAddonType struct {
	OrderItemsAddonType OrderItemsAddonType
	Valid               bool // Valid is true if OrderItemsAddonType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderItemsAddonType) Scan(value interface{}) error {
	if value == nil {
		ns.OrderItemsAddonType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderItemsAddonType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderItemsAddonType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderItemsAddonType), nil
}

func (e OrderItemsAddonType) Valid() bool {
	switch e {
	case OrderItemsAddonTypeSESSION,
		OrderItemsAddonTypeMEAL,
		OrderItemsAddonTypeALLSESSIONSDISCOUNT,
		OrderItemsAddonTypeEARLYDISCOUNT:
		return true
	}
	return false
}

type OrdersEventType string

const (
	OrdersEventTypeALLSESSIONS OrdersEventType = "ALL_SESSIONS"
	OrdersEventTypePERSESSION  OrdersEventType = "PER_SESSION"
	OrdersEventTypePERDAY      OrdersEventType = "PER_DAY"
)

func (e *OrdersEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersEventType(s)
	case string:
		*e = OrdersEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersEventType: %T", src)
	}
	return nil
}

type NullOrdersEventType struct {
	OrdersEventType OrdersEventType
	Valid           bool // Valid is true if OrdersEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersEventType) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersEventType), nil
}

func (e OrdersEventType) Valid() bool {
	switch e {
	case OrdersEventTypeALLSESSIONS,
		OrdersEventTypePERSESSION,
		OrdersEventTypePERDAY:
		return true
	}
	return false
}

type OrdersMealType string

const (
	OrdersMealTypeNONE       OrdersMealType = "NONE"
	OrdersMealTypeREGULAR    OrdersMealType = "REGULAR"
	OrdersMealTypeVEGETARIAN OrdersMealType = "VEGETARIAN"
)

func (e *OrdersMealType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersMealType(s)
	case string:
		*e = OrdersMealType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersMealType: %T", src)
	}
	return nil
}

type NullOrdersMealType struct {
	OrdersMealType OrdersMealType
	Valid          bool // Valid is true if OrdersMealType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersMealType) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersMealType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersMealType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersMealType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersMealType), nil
}

func (e OrdersMealType) Valid() bool {
	switch e {
	case OrdersMealTypeNONE,
		OrdersMealTypeREGULAR,
		OrdersMealTypeVEGETARIAN:
		return true
	}
	return false
}

type OrdersStatus string

const (
	OrdersStatusDRAFT     OrdersStatus = "DRAFT"
	OrdersStatusCONFIRMED OrdersStatus = "CONFIRMED"
	OrdersStatusCANCELLED OrdersStatus = "CANCELLED"
	OrdersStatusONSITE    OrdersStatus = "ON_SITE"
)

func (e *OrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersStatus(s)
	case string:
		*e = OrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersStatus: %T", src)
	}
	return nil
}

type NullOrdersStatus struct {
	OrdersStatus OrdersStatus
	Valid        bool // Valid is true if OrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersStatus), nil
}

func (e OrdersStatus) Valid() bool {
	switch e {
	case OrdersStatusDRAFT,
		OrdersStatusCONFIRMED,
		OrdersStatusCANCELLED,
		OrdersStatusONSITE:
		return true
	}
	return false
}

type PaymentsStatus string

const (
	PaymentsStatusPENDING  PaymentsStatus = "PENDING"
	PaymentsStatusPAID     PaymentsStatus = "PAID"
	PaymentsStatusFAILED   PaymentsStatus = "FAILED"
	PaymentsStatusEXEMPT   PaymentsStatus = "EXEMPT"
	PaymentsStatusREFUNDED PaymentsStatus = "REFUNDED"
)

func (e *PaymentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentsStatus(s)
	case string:
		*e = PaymentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentsStatus: %T", src)
	}
	return nil
}

type NullPaymentsStatus struct {
	PaymentsStatus PaymentsStatus
	Valid          bool // Valid is true if PaymentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentsStatus), nil
}

func (e PaymentsStatus) Valid() bool {
	switch e {
	case PaymentsStatusPENDING,
		PaymentsStatusPAID,
		PaymentsStatusFAILED,
		PaymentsStatusEXEMPT,
		PaymentsStatusREFUNDED:
		return true
	}
	return false
}

type Addon struct {
	ID        string
	FormID    string
	Title     string
	AddonType AddonsAddonType
	SortOrder int32
	Price     string
	Currency  string
	Hint      sql.NullString
	DateTime  sql.NullTime
	Active    bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type EmergencyContact struct {
	ID           string
	SubmissionID string
	FullName     string
	Email        sql.NullString
	CountryCode  string
	Phone        string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Form struct {
	ID          string
	Title       string
	Description sql.NullString
	FormType    FormsFormType
	StartDate   time.Time
	EndDate     time.Time
	Active      bool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Order struct {
	ID           string
	FormID       string
	SubmissionID string
	Status       OrdersStatus
	Amount       string
	Currency     string
	EventType    OrdersEventType
	MealType     OrdersMealType
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type OrderItem struct {
	ID        string
	OrderID   string
	AddonID   string
	Title     string
	AddonType OrderItemsAddonType
	Price     string
	Currency  string
	DateTime  sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Payment struct {
	ID           string
	OrderID      string
	Status       PaymentsStatus
	Amount       string
	Currency     string
	Method       sql.NullString
	GatewayID    sql.NullString
	Provider     sql.NullString
	ErrorMessage sql.NullString
	Meta         json.RawMessage
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type RateLimit struct {
	Ip          string
	WindowStart int32
	Count       int32
}

type Submission struct {
	ID               string
	FormID           string
	FirstName        string
	LastName         string
	Email            string
	IDType           string
	IDValue          string
	CountryCode      string
	Phone            string
	ArrivalDate      sql.NullTime
	DepartureDate    sql.NullTime
	MedicalInsurance sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}
