// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package database

import (
	"context"
	"database/sql"
	"strings"
)

const getSubmissionsReport = `-- name: GetSubmissionsReport :many
SELECT 
    s.id,
    s.first_name,
    s.last_name,
    s.email,
    s.id_type,
    s.id_value,
    s.country_code,
    s.phone,

    o.status,
    o.amount,
    o.currency,
    o.event_type,
    o.meal_type,
    o.created_at,

    COALESCE(counts.session_count, 0) AS session_count,
    COALESCE(counts.meal_count, 0) AS meal_count
FROM submissions s
JOIN orders o ON s.id = o.submission_id AND o.status IN (/*SLICE:status*/?)
LEFT JOIN (
    SELECT order_id,
           SUM(CASE WHEN addon_type = 'SESSION' THEN 1 ELSE 0 END) AS session_count,
           SUM(CASE WHEN addon_type = 'MEAL' THEN 1 ELSE 0 END) AS meal_count
    FROM order_items
    WHERE addon_type IN ('SESSION', 'MEAL')
    GROUP BY order_id
) counts ON counts.order_id = o.id
WHERE s.form_id IN (/*SLICE:ids*/?)
ORDER BY o.created_at DESC
`

type GetSubmissionsReportParams struct {
	Status []OrdersStatus
	Ids    []string
}

type GetSubmissionsReportRow struct {
	ID           string
	FirstName    string
	LastName     string
	Email        string
	IDType       string
	IDValue      string
	CountryCode  string
	Phone        string
	Status       OrdersStatus
	Amount       string
	Currency     string
	EventType    OrdersEventType
	MealType     OrdersMealType
	CreatedAt    sql.NullTime
	SessionCount interface{}
	MealCount    interface{}
}

func (q *Queries) GetSubmissionsReport(ctx context.Context, arg GetSubmissionsReportParams) ([]GetSubmissionsReportRow, error) {
	query := getSubmissionsReport
	var queryParams []interface{}
	if len(arg.Status) > 0 {
		for _, v := range arg.Status {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:status*/?", strings.Repeat(",?", len(arg.Status))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:status*/?", "NULL", 1)
	}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSubmissionsReportRow{}
	for rows.Next() {
		var i GetSubmissionsReportRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.IDType,
			&i.IDValue,
			&i.CountryCode,
			&i.Phone,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.EventType,
			&i.MealType,
			&i.CreatedAt,
			&i.SessionCount,
			&i.MealCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
