// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package database

import (
	"context"
	"database/sql"
	"strings"
)

const getSubmissionsReport = `-- name: GetSubmissionsReport :many
SELECT 
    s.id,
    s.first_name,
    s.last_name,
    s.email,
    s.id_type,
    s.id_value,
    s.country_code,
    s.phone,

    o.status,
    o.amount,
    o.currency,
    o.event_type,
    o.meal_type,
    o.created_at,

    (SELECT COUNT(*) 
     FROM order_items i 
     WHERE i.order_id = o.id AND i.addon_type = 'SESSION'
    ) AS session_count,

    (SELECT COUNT(*) 
     FROM order_items i 
     WHERE i.order_id = o.id AND i.addon_type = 'MEAL'
    ) AS meal_count
FROM submissions s
JOIN orders o ON s.id = o.submission_id AND o.status IN (/*SLICE:status*/?)
WHERE s.form_id IN (/*SLICE:ids*/?)
ORDER BY o.created_at DESC
`

type GetSubmissionsReportParams struct {
	Status []OrdersStatus
	Ids    []string
}

type GetSubmissionsReportRow struct {
	ID           string
	FirstName    string
	LastName     string
	Email        string
	IDType       string
	IDValue      string
	CountryCode  string
	Phone        string
	Status       OrdersStatus
	Amount       string
	Currency     string
	EventType    OrdersEventType
	MealType     OrdersMealType
	CreatedAt    sql.NullTime
	SessionCount int64
	MealCount    int64
}

func (q *Queries) GetSubmissionsReport(ctx context.Context, arg GetSubmissionsReportParams) ([]GetSubmissionsReportRow, error) {
	query := getSubmissionsReport
	var queryParams []interface{}
	if len(arg.Status) > 0 {
		for _, v := range arg.Status {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:status*/?", strings.Repeat(",?", len(arg.Status))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:status*/?", "NULL", 1)
	}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSubmissionsReportRow{}
	for rows.Next() {
		var i GetSubmissionsReportRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.IDType,
			&i.IDValue,
			&i.CountryCode,
			&i.Phone,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.EventType,
			&i.MealType,
			&i.CreatedAt,
			&i.SessionCount,
			&i.MealCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
