// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package database

import (
	"context"
	"database/sql"
)

const getSubmissionsReport = `-- name: GetSubmissionsReport :many
SELECT 
    s.id,
    s.first_name,
    s.last_name,
    s.email,
    s.id_type,
    s.id_value,
    s.country_code,
    s.phone,

    o.status,
    o.amount,
    o.currency,
    o.event_type,
    o.meal_type,
    o.created_at,

    (SELECT COUNT(*) 
     FROM order_items i 
     WHERE o.order_id = o.id AND i.addon_type = 'SESSION'
    ) AS session_count,

    (SELECT COUNT(*) 
     FROM order_items i 
     WHERE o.order_id = o.id AND i.addon_type = 'MEAL'
    ) AS meal_count
FROM submissions s
LEFT JOIN orders o ON s.id = o.submission_id
WHERE s.form_id = ?
ORDER BY o.created_at DESC
`

type GetSubmissionsReportRow struct {
	ID           string
	FirstName    string
	LastName     string
	Email        string
	IDType       string
	IDValue      string
	CountryCode  string
	Phone        string
	Status       NullOrdersStatus
	Amount       sql.NullString
	Currency     sql.NullString
	EventType    NullOrdersEventType
	MealType     NullOrdersMealType
	CreatedAt    sql.NullTime
	SessionCount int64
	MealCount    int64
}

func (q *Queries) GetSubmissionsReport(ctx context.Context, formID string) ([]GetSubmissionsReportRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubmissionsReport, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSubmissionsReportRow{}
	for rows.Next() {
		var i GetSubmissionsReportRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.IDType,
			&i.IDValue,
			&i.CountryCode,
			&i.Phone,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.EventType,
			&i.MealType,
			&i.CreatedAt,
			&i.SessionCount,
			&i.MealCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
